### ISSUE TITLE
[Crash] Crash while loading involving "layer renderer"

### ISSUE THREAD

**Issue by Corvus20** [MachineMuse/Numina#36]
I don't really know what all is going on here beyond that. Maybe you could figure it out?
[crash-2021-10-31_14.26.55-fml.txt](https://github.com/MachineMuse/Numina/files/7449493/crash-2021-10-31_14.26.55-fml.txt)

**Comment by NighthowlerStudios** [comment]
java.lang.NullPointerException
	at com.github.lehjr.numina.util.client.event.ArmorLayerSetup.addCustomArmorLayer(ArmorLayerSetup.java:70)
	at com.github.lehjr.numina.util.client.event.ArmorLayerSetup.loadComplete(ArmorLayerSetup.java:62)
	at com.github.lehjr.numina.basemod.Numina$MyStaticClientOnlyEventHandler.loadComplete(Numina.java:142)
	at net.minecraftforge.eventbus.ASMEventHandler_444_MyStaticClientOnlyEventHandler_loadComplete_FMLLoadCompleteEvent.invoke(.dynamic)
	

looks like a thread collision that sometimes occur if one registry thread is ahead of the other as loadComplete might get fired too soon.

**Comment by NighthowlerStudios** [comment]
to be clear I just had this crash too, and it is entirely random
